/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-02-05 00:43:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.io.PrintWriter;
import DAO.dao;
import com.mysql.fabric.Response;
import java.awt.dnd.DropTargetListener;
import java.util.ArrayList;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.io.PrintWriter;
import DTO.Board;
import org.apache.tomcat.util.buf.Utf8Encoder;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 String hardware = "hardware";
	String liquid = "liquid";
	String coil = "coil";
	int nforhardware = 1;
	int nforliquid = 2;
	int nforcoil = 3;
	
	String Menuhardware_sql = "select * from products where producttype = 'hardware'";
	String Menuliquid_sql = "select * from products where producttype = 'liquid'";
	String Menucoil_sql = "select * from products where producttype = 'coil'";
	
	
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1612484697788L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Documents/eclipse/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/VapeWeb/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1612484698593L));
    _jspx_dependants.put("/submenu.jsp", Long.valueOf(1612484698594L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1612484679932L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("DTO.Board");
    _jspx_imports_classes.add("com.mysql.fabric.Response");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("org.apache.tomcat.util.buf.Utf8Encoder");
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("DAO.dao");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.awt.dnd.DropTargetListener");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/custom.css\">\t\r\n");
      out.write("\t<title>JASET VAPE</title>\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/custom.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/gh/stove99/jquery-modal-sample@v1.4/css/animate.min.css\" />\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/gh/stove99/jquery-modal-sample@v1.4/css/jquery.modal.css\" />\r\n");
      out.write("\t<title>JASET VAPE</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("div {text-align: center;}\r\n");
      out.write(".form {\r\n");
      out.write("    float: right;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t");

		String id = null;
		if	(session.getAttribute("id") != null) {
		id = (String) session.getAttribute("id");
		}
	
      out.write("\r\n");
      out.write("    ");

    	if(id == null) {
   	
      out.write("\t\t\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">  \r\n");
      out.write("   \t\t<div class=\"d-flex flex-grow-1\"> \r\n");
      out.write("        \t<div class=\"w-100 text-right\">\r\n");
      out.write("            \t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" >\r\n");
      out.write("                \t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            \t</button>\r\n");
      out.write("        \t</div>\r\n");
      out.write("    \t</div>  \r\n");
      out.write("\r\n");
      out.write("\t    <div class=\"collapse navbar-collapse flex-grow-1 text-right\">\r\n");
      out.write("    \t    <ul class=\"navbar-nav ml-auto flex-nowrap\">\r\n");
      out.write("        \t    <li class=\"nav-item active\">\r\n");
      out.write("            \t    <a class=\"nav-link\" href=\"login.jsp\">로그인</a>\r\n");
      out.write("            \t</li>\r\n");
      out.write("            \t<li class=\"nav-item\">\r\n");
      out.write("                \t<a class=\"nav-link\" href=\"join.jsp\">회원가입</a>\r\n");
      out.write("\t            </li>\r\n");
      out.write("    \t        <li class=\"nav-item\">\r\n");
      out.write("        \t        <a class=\"nav-link\" href=\"myshopping.jsp\" onclick=\"checkForm(); return false;\">나의 쇼핑</a>\r\n");
      out.write("\t            </li>\r\n");
      out.write("    \t    </ul>\r\n");
      out.write("    \t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t");

    	} else {
    
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">  \r\n");
      out.write("   \t<div class=\"d-flex flex-grow-1\"> \r\n");
      out.write("        \t<div class=\"w-100 text-right\">\r\n");
      out.write("            \t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" >\r\n");
      out.write("                \t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            \t</button>\r\n");
      out.write("        \t</div>\r\n");
      out.write("    \t</div>  \r\n");
      out.write("\r\n");
      out.write("\t    <div class=\"collapse navbar-collapse flex-grow-1 text-right\">\r\n");
      out.write("    \t    <ul class=\"navbar-nav ml-auto flex-nowrap\">\r\n");
      out.write("        \t    <li class=\"nav-item active\">\r\n");
      out.write("            \t    <a class=\"nav-link\" href=\"logout.jsp\">로그아웃</a>\r\n");
      out.write("            \t</li>\r\n");
      out.write("            \t<li class=\"nav-item\">\r\n");
      out.write("                \t<a class=\"nav-link\" href=\"update.jsp\">회원수정</a>\r\n");
      out.write("            \t</li>\r\n");
      out.write("            \t<li class=\"nav-item\">\r\n");
      out.write("                \t<a class=\"nav-link\" href=\"myshopping.jsp\">나의 쇼핑</a>\r\n");
      out.write("            \t</li>\r\n");
      out.write("            \t");

            		String admin = (String) session.getAttribute("admin");
            		if(admin == null)
            			admin = "0";
            		if(admin.equals("1")) {
            	
      out.write("\r\n");
      out.write("            \t<li class=\"nav-item\">\r\n");
      out.write("                \t<a data-toggle=\"modal\" href=\"#myModal\" class=\"nav-link\">관리자 권한 부여</a>\r\n");
      out.write("            \t</li>\r\n");
      out.write("            \t");
}
      out.write("\r\n");
      out.write("        \t</ul>\r\n");
      out.write("    \t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("    ");
 	
    	}
	
      out.write("\r\n");
      out.write("  <form action=\"setadmin.jsp\" method =\"post\">\r\n");
      out.write("\t  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\"> <!-- 사용자 지정 부분① : id명 -->\r\n");
      out.write("\t    <div class=\"modal-dialog\">\r\n");
      out.write("\t      <!-- Modal content-->\r\n");
      out.write("\t      <div class=\"modal-content\">\r\n");
      out.write("\t        <div class=\"modal-header\">\r\n");
      out.write("\t          <h4 class=\"modal-title\">관리자 등록</h4> <!-- 사용자 지정 부분② : 타이틀 -->\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"modal-body\">\r\n");
      out.write("\t          \t<label for=\"userid\">아이디\r\n");
      out.write("\t          \t<input type=\"text\" name=\"userid\" value=\"\">\r\n");
      out.write("\t          \t</label> <!-- 사용자 지정 부분③ : 텍스트 메시지 -->\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"modal-footer\">\r\n");
      out.write("\t          <button type=\"submit\" class=\"btn btn-default\">등록</button>\r\n");
      out.write("\t          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("  </form>\r\n");
      out.write("<br>\r\n");
      out.write("<div ><a href=\"main.jsp\"><img src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"/></a></div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"item1\">\r\n");
      out.write("  <form onsubmit=\"return checkForm2();\" class=\"form-inline\" action=\"Productsalespage.jsp\"><input class=\"form-control mr-sm-2 \" name=\"search\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("  <button class=\"btn bg-dark text-white btn-outline-white my-2 my-sm-0 {background-color: #223a6b !important;} float-right\" type=\"submit\">Search</button>\r\n");
      out.write("  </form>\r\n");
      out.write(" </div>\r\n");
      out.write(" \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   function checkForm2() {\r\n");
      out.write("      if (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id == null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") {\r\n");
      out.write("    \t alert(\"로그인 해주세요.\");\r\n");
      out.write("    \t location.href =\"http://localhost/VapeWeb/login.jsp\";\r\n");
      out.write("    \t return false;\r\n");
      out.write("      } else {\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"//cdn.jsdelivr.net/gh/stove99/jquery-modal-sample@v1.4/js/jquery.modal.js\"></script>\r\n");
      out.write("<script src=\"//cdn.jsdelivr.net/gh/stove99/jquery-modal-sample@v1.4/js/modal.js\"></script>\r\n");
      out.write("<script src=\"js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"css/bootstrap.min.css\"></script>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/custom.css\">\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<div class=\"d-flex justify-content-around\">\r\n");
      out.write("  <div id=\"submenu\"><a href=\"#\" onclick=\"javascript:checkForm('");
      out.print(hardware);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(nforhardware);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print("aaa");
      out.write("')\">하드웨어</a></div>\r\n");
      out.write("  <div id=\"submenu\"><a href=\"#\" onclick=\"javascript:checkForm('");
      out.print(liquid);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(nforliquid);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print("aaa");
      out.write("')\">원본액상</a></div>\r\n");
      out.write("  <div id=\"submenu\"><a href=\"#\" onclick=\"javascript:checkForm('");
      out.print(coil);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(nforcoil);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print("aaa");
      out.write("')\">코일</a></div>\r\n");
      out.write("  <div id=\"submenu\"><a href=\"community.jsp\">커뮤니티</a></div>\r\n");
      out.write("       \r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");
      out.write("<form name=\"frm\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"producttype\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"orderbyint\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"sqlQuery\">\r\n");
      out.write("</form>\r\n");

	String id2 = (String)session.getAttribute("id");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   function checkForm(producttype,orderbyint,sqlQuery) {\r\n");
      out.write("      if (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id==null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") {\r\n");
      out.write("         alert(\"로그인 해주세요.\");\r\n");
      out.write("         location.href = \"login.jsp\";\r\n");
      out.write("      } else if (");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id != null}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") {\r\n");
      out.write("    \t  //alert(\"id가 들어왔음\");\r\n");
      out.write("    \t  f=document.frm;\r\n");
      out.write("    \t  f.producttype.value=producttype;\r\n");
      out.write("    \t  f.orderbyint.value=orderbyint;\r\n");
      out.write("    \t  f.sqlQuery.value=sqlQuery;\r\n");
      out.write("    \t  f.action = \"Productsalespage.jsp\";\r\n");
      out.write("    \t  f.submit();\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container mt-5\" style=\"max-width: 600px;\">\r\n");
      out.write("\t\t <form method=\"post\" action=\"joinAction.jsp\">\r\n");
      out.write("\t\t <h3 style=\"text-align: center;\">회원가입</h3>\r\n");
      out.write(" \t\t <div class=\"form-group\">\r\n");
      out.write("   \t\t\t<label style=\"float: left;\">아이디</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"id\" maxlength=\"20\">\r\n");
      out.write("\t\t </div>\r\n");
      out.write(" \t\t <div class=\"form-group\">\r\n");
      out.write("   \t\t\t<label style=\"float: left;\">비밀번호</label>\r\n");
      out.write("\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"pw\" maxlength=\"20\">\r\n");
      out.write("\t\t </div>\r\n");
      out.write(" \t\t <div class=\"form-group\">\r\n");
      out.write("   \t\t\t<label style=\"float: left;\">주소</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\"  id=\"sample4_postcode\" placeholder=\"우편번호\" name=\"zip\" maxlength=\"20\"> <input type=\"button\"  onclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\"><br>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"sample4_roadAddress\"  placeholder=\"도로명주소\" name=\"street\" maxlength=\"100\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"sample4_jibunAddress\" placeholder=\"지번주소\" name=\"street\" maxlength=\"100\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"sample4_detailAddress\" placeholder=\"상세주소\" name=\"building\" maxlength=\"100\">\r\n");
      out.write("\t\t\t\t<span id=\"guide\" style=\"color:#999;display:none\"></span>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"sample4_extraAddress\" placeholder=\"*\" maxlength=\"100\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t <script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("  \t  \t//본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("    \t\tfunction sample4_execDaumPostcode() {\r\n");
      out.write("        \t\tnew daum.Postcode({\r\n");
      out.write("            \t\toncomplete: function(data) {\r\n");
      out.write("                \t\t// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                \t\t// 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\r\n");
      out.write("                \t\t// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                \t\tvar roadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("                \t\tvar extraRoadAddr = ''; // 참고 항목 변수\r\n");
      out.write("\t\t\r\n");
      out.write("        \t\t        // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("\t\t                // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("        \t\t        if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                \t\t    extraRoadAddr += data.bname;\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t// 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                \t\tif(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                   \t\textraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                \t\t}\r\n");
      out.write("                \t\t// 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                \t\tif(extraRoadAddr !== ''){\r\n");
      out.write("                    \t\textraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("                \t\t}\r\n");
      out.write("\r\n");
      out.write("                \t\t// 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                \t\tdocument.getElementById('sample4_postcode').value = data.zonecode;\r\n");
      out.write("\t\t                document.getElementById(\"sample4_roadAddress\").value = roadAddr;\r\n");
      out.write("        \t\t        document.getElementById(\"sample4_jibunAddress\").value = data.jibunAddress;\r\n");
      out.write("                \r\n");
      out.write("                \t\t// 참고항목 문자열이 있을 경우 해당 필드에 넣는다.\r\n");
      out.write("                \t\tif(roadAddr !== ''){\r\n");
      out.write("                    \t\tdocument.getElementById(\"sample4_extraAddress\").value = extraRoadAddr;\r\n");
      out.write("                \t\t} else {\r\n");
      out.write("                    \t\tdocument.getElementById(\"sample4_extraAddress\").value = '';\r\n");
      out.write("                \t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t                var guideTextBox = document.getElementById(\"guide\");\r\n");
      out.write("        \t\t        // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\r\n");
      out.write("                \t\tif(data.autoRoadAddress) {\r\n");
      out.write("                    \t\tvar expRoadAddr = data.autoRoadAddress + extraRoadAddr;\r\n");
      out.write("                    \t\tguideTextBox.innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';\r\n");
      out.write("                    \t\tguideTextBox.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("\t\t                } else if(data.autoJibunAddress) {\r\n");
      out.write("        \t\t            var expJibunAddr = data.autoJibunAddress;\r\n");
      out.write("                \t\t    guideTextBox.innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';\r\n");
      out.write("                    \t\tguideTextBox.style.display = 'block';\r\n");
      out.write("                \t\t} else {\r\n");
      out.write("                    \t\tguideTextBox.innerHTML = '';\r\n");
      out.write("                    \t\tguideTextBox.style.display = 'none';\r\n");
      out.write("                \t\t}\r\n");
      out.write("            \t\t}\r\n");
      out.write("        \t\t}).open();\r\n");
      out.write("\t \t   }\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write(" \t\t</div>\r\n");
      out.write("\t\t <div class=\"form-group\">\r\n");
      out.write("   \t\t\t<label style=\"float: left;\">핸드폰 번호</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"mobile\" maxlength=\"20\">\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t\t <div class=\"form-group\">\r\n");
      out.write("   \t\t\t<label style=\"float: left;\">생년월일</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"birthday\" maxlength=\"20\">\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t\t \r\n");
      out.write("  \t\t\t<button type=\"submit\" class=\"btn btn-primary \">회원가입</button>\r\n");
      out.write("  \t\t\t<button type=\"button\" class=\"btn btn-primary ml-3\" name=\"cancle_home\" onclick=\"sendit();\">취소</button>\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t</form>\r\n");
      out.write("\t</div> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("<br><br><br><br><br><br><br><br>\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("  <div class=\"col-md-2\" style=\"background-color:#141E3D;\"><img src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"/></div>\r\n");
      out.write("  <div class=\"col-md-10\" style=\"background-color:#141E3D;\"><p><a style=\"color:white;\" href=\"https://github.com/parka01\">박아영 |</a>\r\n");
      out.write("\t\t\t<a style=\"color:white;\" href=\"https://github.com/satelite54\">김태헌 |</a>\r\n");
      out.write("\t\t\t<a style=\"color:white;\" href=\"https://github.com/curong\">정재우 |</a>\r\n");
      out.write("\t\t\t<a style=\"color:white;\" href=\"https://github.com/franksausageocean\">이세준</a><p style=\"color:white;\" id=\"address\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<span >법인명(상호): 자셋베잎</span>\r\n");
      out.write("\t\t\t\t\t\t<span>대표자(성명): 자셋</span>\r\n");
      out.write("\t\t\t\t\t\t<span>사업자 등록번호안내: 123-45-67891</span>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<span>통신판매업 신고 2021-부산진구-1234</span>\r\n");
      out.write("\t\t\t\t\t\t<span>[사업자정보확인]</span>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<span>전화: 051-123-4567</span>\r\n");
      out.write("\t\t\t\t\t\t<span>팩스: 051-123-4567</span>\r\n");
      out.write("\t\t\t\t\t\t<span>주소: 부산광역시 진구 IT로 30 5층</span>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t</p>\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</footer>");
      out.write("  \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction sendit(){\r\n");
      out.write("\t\tlocation.href =\"http://localhost/VapeWeb/main.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<script src=\"js/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"css/bootstrap.min.css\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /menu.jsp(127,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/img/logo.png");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /footer.jsp(7,68) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/img/logo2.jpg");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }
}
