/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2020-04-09 05:23:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch04;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gugudan_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
request.setCharacterEncoding("EUC-KR");
      out.write("\r\n");
      out.write("<h1>구구단 리스트</h1>\r\n");
      out.write("1.<a href=\"http://192.168.0.84/myapp/ch04/gugudan.jsp\">강사PC</a><br/>\r\n");
      out.write("2.<a href=\"http://192.168.0.24/myapp/ch04/gugudan.jsp\">양지민</a><br/>\r\n");
      out.write("3.<a href=\"http://192.168.0.66/myapp/ch04/gugudan.jsp\">박한준</a><br/>\r\n");
      out.write("4.<a href=\"http://192.168.0.6/myapp/ch04/gugudan.jsp\">최상희</a><br/>\r\n");
      out.write("5.<a href=\"http://192.168.0.75/myapp/ch04/gugudan.jsp\">이희주</a><br/>\r\n");
      out.write("6.<a href=\"http://192.168.0.67/myapp/ch04/gugudan.jsp\">이승규</a><br/>\r\n");
      out.write("7.<a href=\"http://192.168.0.9/myapp/ch04/gugudan.jsp\">허학신</a><br/>\r\n");
      out.write("8.<a href=\"http://192.168.0.37/myapp/ch04/gugudan.jsp\">김아미솔</a><br/>\r\n");
      out.write("9.<a href=\"http://192.168.0.16/myapp/ch04/gugudan.jsp\">김준택</a><br/>\r\n");
      out.write("10.<a href=\"http://192.168.0.14/myapp/ch04/gugudan.jsp\">송하민</a><br/>\r\n");
      out.write("11.<a href=\"http://192.168.0.73/myapp/ch04/gugudan.jsp\">조명윤</a><br/>\r\n");
      out.write("12.<a href=\"http://192.168.0.17/myapp/ch04/gugudan.jsp\">김원상</a><br/>\r\n");
      out.write("13.<a href=\"http://192.168.0.15/myapp/ch04/gugudan.jsp\">조현승</a><br/>\r\n");
      out.write("14.<a href=\"http://192.168.0.13/myapp/ch04/gugudan.jsp\">최수지</a><br/>\r\n");
      out.write("15.<a href=\"http://192.168.0.156/myapp/ch04/gugudan.jsp\">이윤지</a><br/>\r\n");
      out.write("16.<a href=\"http://192.168.0.80/myapp/ch04/gugudan.jsp\">김광록</a><br/>\r\n");
      out.write("17.<a href=\"http://192.168.0.83/myapp/ch04/gugudan.jsp\">박정인</a><br/>\r\n");
      out.write("18.<a href=\"http://192.168.0.12/myapp/ch04/gugudan.jsp\">김유진</a><br/>\r\n");
      out.write("19.<a href=\"http://192.168.0.55/myapp/ch04/gugudan.jsp\">이은향</a><br/>\r\n");
      out.write("20.<a href=\"http://192.168.0.58/myapp/ch04/gugudan.jsp\">강재홍</a><br/>\r\n");
      out.write("21.<a href=\"http://192.168.0./myapp/ch04/gugudan.jsp\">김하민_</a><br/>\r\n");
      out.write("22.<a href=\"http://192.168.0./myapp/ch04/gugudan.jsp\">성승우_</a><br/>\r\n");
      out.write("23.<a href=\"http://192.168.0./myapp/ch04/gugudan.jsp\">신희만_</a><br/>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
